sudo: required
services:
  - docker

before_install:
  - docker build -t tomekde/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tomekde/react-test npm test

after_success:
  - docker build -t tomekde/multi-client ./client
  - docker build -t tomekde/multi-nginx ./nginx
  - docker build -t tomekde/multi-server ./server
  - docker build -t tomekde/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tomekde/multi-client
  - docker push tomekde/multi-nginx
  - docker push tomekde/multi-server
  - docker push tomekde/multi-worker